# Generated by Django 4.2 on 2023-05-02 09:18

import biblioteka.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expiry_date',
            field=models.DateTimeField(default=biblioteka.models.expiry),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='issued_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
